#!/bin/bash

# Define the API URL for Pikachu
API_URL="https://pokeapi.co/api/v2/pokemon/pikachu" 

if ! curl -sf "$API_URL" > data.json; then
    #if curl fails, write the error to the errors.txt file
    echo "Error: Failed to fetch data from the API ${API_URL}" > errors.txt
    exit 1
fi

#check if data.json was created and not empty
if [ -s data.json ]; then
    echo "Success! Pikachu data has been saved to data.json" > errors.txt
    exit 1
else 
    echo  "API was successful, but no data was saved to data.json" > errors.txt
    rm data.json
    exit 1
fi
